artifact_uri: file:C:\Users\Santosh\Desktop\ML-Project-Deployment\MLOPS\House-Price-prediction-End-to-End-Project\mlruns_local/329743566109862875/91abedf68dea44cb9ca1c617944aedb3/artifacts
end_time: 1771670228074
entry_point_name: ''
experiment_id: '329743566109862875'
lifecycle_stage: active
run_id: 91abedf68dea44cb9ca1c617944aedb3
run_name: ml_pipeline-2026_02_21-10_36_54_674600
run_uuid: 91abedf68dea44cb9ca1c617944aedb3
source_name: ''
source_type: 4
source_version: ''
start_time: 1771670224041
status: 3
tags: []
user_id: Santosh
